### ISSUE TITLE
[ w5-Visualization-project](Pedro Jódar)

### ISSUE THREAD

**Issue by Periclates7** [Ironhack-Data-Madrid-Enero-2023/w5-Visualization-project#1]
https://github.com/Periclates7/Tableau-Project

**Comment by fjgarciaes** [comment]
Muy buen trabajo Pedro! El readme esta muy bien explicado y hace que sea fácil entender el trabajo que has ido realizando aun sin conocer el tema, algunas de las imágenes se ven un poco pequeñas lo que hace un poco difícil verlas ahi, pero dentro de tableau se ve que todo tiene sentido y el proceso que has seguido me parece muy bueno. Enhorabuena por este trabajo.
