### ISSUE TITLE
[w5-Visualization-project](Manuel Zerpa)

### ISSUE THREAD

**Issue by Manuelzerpadl** [Ironhack-Data-Madrid-Enero-2023/w5-Visualization-project#11]
https://github.com/Manuelzerpadl/Proyecto-Viz

**Comment by fjgarciaes** [comment]
Buen trabajo Manuel. El readme y el trabajo esta bien estructurado y con sentido. Las gráficas resultan interesantes y ayudan y aclaran lo que quieres explicar. Intenta añadir el link de tableau o de powerbi y que el formato del readme sea el mismo en todas las frases.
