### ISSUE TITLE
[Visualization Project] (Cristian Gómez)

### ISSUE THREAD

**Issue by crisgo-data** [Ironhack-Data-Madrid-Enero-2023/w5-Visualization-project#13]
https://github.com/crisgo-data/Visualization-project

**Comment by OrianAmpuero** [comment]
Excelente trabajo Cristian!! Buena visualización de datos; en cuanto al readme bien estructurado y desarrollado.  La presentación trata de mejorar el inicio (saludo), buen resumen de los datos y apoyo visual
