### ISSUE TITLE
[w5-Visualization-project](Ronald Hernandez)

### ISSUE THREAD

**Issue by Ronher1992** [Ironhack-Data-Madrid-Enero-2023/w5-Visualization-project#14]
https://github.com/Ronher1992/Project_Viz

**Comment by fjgarciaes** [comment]
Buen trabajo Ronald. El dashboard y las gráficas son explicativas de los datos con los que estabas trabajando. Trata de echarle un ojo al readme para chequear palabras que puedan estar mal escritas así como en los títulos de las gráficas.
