### ISSUE TITLE
[w5-Visualization-project](Alfonso Urra)

### ISSUE THREAD

**Issue by AlfonsoUrra** [Ironhack-Data-Madrid-Enero-2023/w5-Visualization-project#16]
https://github.com/AlfonsoUrra/w-5-visualization-data

**Comment by OrianAmpuero** [comment]
Buen trabajo Alfonso! Has hecho buen uso de los datos y lograste plasmar los insights de manera correcta; cuidado con la visualización ya que se podía ajustar algunos limites para no ver tantos espacios. En cuanto a la presentación:
- Trata de no decir lo malo porque nadie lo sabe
- Mejora el inicio (saludo)
- Seguir conversando para no perder al público cuando esperas las imágenes
- Bien el dar ejemplos para hacer mas amena la conversación
