### ISSUE TITLE
[Pueblos trasnacionales](Santiago Fuentes) 

### ISSUE THREAD

**Issue by santiagofp9** [Ironhack-Data-Madrid-Enero-2023/w5-Visualization-project#19]

**Comment by fjgarciaes** [comment]
Bien Santi. Has hecho un buen trabajo con los datos pero recuerda que este proyecto era visualización y no se vio nada de ese trabajo, así que te animo a seguir currando y mejorar el proyecto.
En cuanto a la presentación el inicio ha estado bien pero trata de ajustarte mas al tiempo.

**Comment by santiagofp9** [comment]
Tienes razón, en la visualización voy muy atrasado, apenas estoy estudiando
a detalle la documentación de Kepler.

Durante la semana me quedé muy rezagado con Tableau y Power BI, pero igual
sospecho que no iba a ser posible graficar por municipio ni mucho menos por
"entidad singular" en ninguno de los dos. Aunque quizá de cara al
empaquetado final sí que puedo insertar solo el mapa en html que produce
Kepler.

Sobre la presentación, para la presentación final escribiré un par de
guiones de pitch, para 3 y 7 min. También procuraré descansar antes de
presentar, soy mucho más elocuente y sintético cuando duermo más de 3 horas.

Gracias!
