### ISSUE TITLE
[ w5-Visualization-project](Paula Bendito Buhles)

### ISSUE THREAD

**Issue by paulabnbh** [Ironhack-Data-Madrid-Enero-2023/w5-Visualization-project#2]
https://github.com/paulabnbh/Visualization-project

**Comment by fjgarciaes** [comment]
Buen trabajo Paula. El análisis de los datos esta bien realizado y el dashboard de tableau es explicativo en función de lo que has querido mostrar qué era la parte más importante del proyecto. En el readme trata de poner imágenes cuando estes hablando del dashboard ya que evitas que quien quiera verlo tenga que estar buscándolo y trata de reducir un poco el texto. En cuanto a las conclusiones están bien pero igual la que contiene una pregunta no debería estar ahi ya que no es una conclusion como tal, échale un ojo. Muy buen proyecto.
