### ISSUE TITLE
[w5-Visualization-project](Rafael Calbacho)

### ISSUE THREAD

**Issue by Calbacho** [Ironhack-Data-Madrid-Enero-2023/w5-Visualization-project#21]
https://github.com/Calbacho/Visualizations

**Comment by fjgarciaes** [comment]
Muy buen trabajo Rafa! Tanto el readme como las gráficas están bien y son muy explicativas. Trata de introducir los datos con los que has trabajado en el repo en caso de que alguien quiera revisarlos. Bien por escribir las conclusiones u observaciones que has conseguido a través de la visualización. Felicitaciones por este proyecto.
