### ISSUE TITLE
[ w5-Visualization-project](ruben.francisco)

### ISSUE THREAD

**Issue by segomismo** [Ironhack-Data-Madrid-Enero-2023/w5-Visualization-project#22]
https://github.com/segomismo/5-Proyecto-Viz.git

**Comment by fjgarciaes** [comment]
Buen trabajo Ruben. Al tratarse de un proyecto de visualización, a pesar de que tu readme esta muy bien explicado, trata de no incluir código y quizás las imágenes de las gráficas en vez de los links. También creo que seria mas eficiente que esos links fuesen dashboard distintos de una historia bajo un único link ya que lo hace más sencillo. Por lo demás todo bien, sigue así.
