### ISSUE TITLE
[w5-Visualization-project](Paula García)

### ISSUE THREAD

**Issue by pgmar257** [Ironhack-Data-Madrid-Enero-2023/w5-Visualization-project#24]
https://github.com/pgmar257/Project-VIZ.git

**Comment by fjgarciaes** [comment]
Excelente trabajo Paula. Tanto el dashboard como el readme esta muy bien, los gráficos son explicativos y la información que aportan es muy interesante. Lo único que quizás el dashboard este un poco cargado con tantos gráficos y lo podrías separar en mas hojas pero por lo demás es un trabajo muy completo así que te felicito por ello aunque me hubiese gustado verte presentando. Sigue así que este es el camino!!
