### ISSUE TITLE
[w5-Visualization-project](Jorge Mendoza)

### ISSUE THREAD

**Issue by jmgpgit** [Ironhack-Data-Madrid-Enero-2023/w5-Visualization-project#3]
https://github.com/jmgpgit/Visualisation-Project

**Comment by fjgarciaes** [comment]
Buen trabajo Jorge. Has cumplido con los objetivos que se pedían y el readme es explicativo de tu trabajo aunque intenta añadir alguna imagen o quizás algunos iconos para que la ultima parte no sea tanto texto.
