### ISSUE TITLE
[Proyecto Visualización] (Bea Zatarain)

### ISSUE THREAD

**Issue by BeaZatarain** [Ironhack-Data-Madrid-Enero-2023/w5-Visualization-project#4]
https://github.com/BeaZatarain/Proyecto-Visualizacion

**Comment by OrianAmpuero** [comment]
Muy buen trabajo Bea!! Has mejorado mucho desde la primera presentación. Bien resumido y contado los datos, mejora el inicio (saludo) y en cuanto al repo todo correcto aunque cuidado con ese archivo .text que no es nada
