### ISSUE TITLE
Visualization-project (Lohengrin Verde)

### ISSUE THREAD

**Issue by lohe040789** [Ironhack-Data-Madrid-Enero-2023/w5-Visualization-project#5]
https://github.com/lohe040789/-w5-Visualization-project-

**Comment by fjgarciaes** [comment]
Buen trabajo Lohe, el readme esta bien explicado y esta bien que expliques al inicio de que trata el proyecto, trata de mantener el mismo formato con las palabra, por ejemplo todos  los países en mayúsculas, por otro lado dentro del repositorio de tableau igual seria mas interesante si en lugar de una única slide poner mas para que no estén todas las gráficas en una. Sigue así.
