### ISSUE TITLE
[5.Visualization-project](Paula_Alvarez)

### ISSUE THREAD

**Issue by paulaalvarezsa** [Ironhack-Data-Madrid-Enero-2023/w5-Visualization-project#9]

**Comment by fjgarciaes** [comment]
Buen trabajo Paula. Tanto el readme como las gráficas están bien aunque échale un ojo a los limites de las tablas para que no te queden espacios vacíos y que los títulos o leyendas no contengan cosas que no quieres. En cuanto a la presentación bien explicado tu trabajo aunque intenta evitar expresiones "coloquiales" y bien por moverte alrededor del espacio y moverte para explicar las gráficas.
